---
- hosts: all
  become: True
  become_method: sudo
  tasks:

    - name: Unzip the war file
      copy:
        src: /var/lib/jenkins/workspace/project4/target/webapptest.war/ # We have define a html page
        dest: /opt/tomcat/webapps/war/
